// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

import * as v3alpha1 from './v3alpha1';
const AgentsClient = v3alpha1.AgentsClient;
const EntityTypesClient = v3alpha1.EntityTypesClient;
const FlowsClient = v3alpha1.FlowsClient;
const IntentsClient = v3alpha1.IntentsClient;
const PagesClient = v3alpha1.PagesClient;
const SessionEntityTypesClient = v3alpha1.SessionEntityTypesClient;
const SessionsClient = v3alpha1.SessionsClient;
const WebhooksClient = v3alpha1.WebhooksClient;
export {v3alpha1, AgentsClient, EntityTypesClient, FlowsClient, IntentsClient, PagesClient, SessionEntityTypesClient, SessionsClient, WebhooksClient};
export default {v3alpha1, AgentsClient, EntityTypesClient, FlowsClient, IntentsClient, PagesClient, SessionEntityTypesClient, SessionsClient, WebhooksClient};
import * as protos from '../protos/protos';
export {protos}
