apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: "chatserver"
  namespace: "default"
  labels:
    app: "chatserver"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "chatserver"
  template:
    metadata:
      labels:
        app: "chatserver"
    spec:
      containers:
      - name: "chatserver-image"
        image: "gcr.io/${PROJECT_ID}/chatserver-image:latest"
        imagePullPolicy: Always
        env:
          - name: "GOOGLE_APPLICATION_CREDENTIALS"
            value: /var/secrets/master.json
          - name: "GC_PROJECT_ID"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: GC_PROJECT_ID
          - name: "ENV"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: ENV
          - name: "AGENT_ID"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: AGENT_ID
          - name: "CX_LOCATION"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: CX_LOCATION
          - name: "VERTICAL"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: VERTICAL
          - name: "MY_PHONE_NUMBER"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: MY_PHONE_NUMBER
          - name: "LIVE_AGENT_PHONE_NUMBER"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: LIVE_AGENT_PHONE_NUMBER
          - name: "TWILIO_ACCOUNT_SID"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: TWILIO_ACCOUNT_SID
          - name: "TWILIO_ACCOUNT_TOKEN"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: TWILIO_ACCOUNT_TOKEN
          - name: "PUBSUB_TOPIC"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: PUBSUB_TOPIC
          - name: "BQ_LOCATION"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: BQ_LOCATION
          - name: "DATASET"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: DATASET
          - name: "TABLE"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: TABLE
          - name: "DOMAIN1"
            valueFrom:
              configMapKeyRef:
                name: chatserver-config
                key: DOMAIN1
        volumeMounts:
          - name: mykeys
            mountPath: /var/secrets/
            readOnly: true
        ports:
        - containerPort: 8080  
      volumes:
      - name: mykeys
        secret:
          secretName: credentials