apiVersion: v1
kind: Service
metadata:
  name: chatserver-service
spec:
  type: LoadBalancer
  selector:
    app: chatserver
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
      #how other other pods access our pod
    - port: 80
      protocol: TCP
      #port on target pods (multi-client pod) service talks 
      targetPort: 80
