apiVersion: v1
kind: Service
metadata:
  name: chatserver-service
spec:
  type: NodePort
  selector:
    app: chatserver
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: front-end-service
spec:
  type: LoadBalancer
  #loadBalancerIP: 34.95.97.143 
  selector:
    app: front-end
  ports:
      #how other other pods access our pod
    - port: 80
      protocol: TCP
      #port on target pods (multi-client pod) service talks 
      targetPort: 80
