#
# @license
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# =============================================================================
 
steps:
# Build ChatServer Container
# docker build -t gcr.io/$PROJECT_ID/chatserver-image:latest ./backend
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/chatserver-image:latest', './backend' ]
# Push ChatServer Container to Container Registry
# docker push gcr.io/$PROJECT_ID/chatserver-image:latest
- id: 'Push ChatServer image to registry'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/chatserver-image:latest' ]
# Build Web Container
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/web-image', './web' ]
# Push Web Container to Container Registry
- id: 'Push Front-end image to registry'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/web-image:latest' ]
timeout: 1200s